// src/constants/branchMockData.js

export const MOCK_BRANCHES = [
  {
    id: 1,
    code: "001",
    name: "Premier Insurance Corp",
    branch: "Main Branch",
    address: "123 Ayala Ave, Makati City",
    contact: "02-8123-4567",
    email: "info@premier.com",
    manager: "Juan Dela Cruz",
    status: "Active",
    dateCreated: "Jan 15, 2026",
    vouchers: 1250,
  },
  {
    id: 2,
    code: "001",
    name: "Premier Insurance Corp",
    branch: "North Edsa Branch",
    address: "North Edsa, Quezon City",
    contact: "02-8456-7890",
    email: "north@premier.com",
    manager: "Maria Santos",
    status: "Active",
    dateCreated: "Feb 10, 2026",
    vouchers: 450,
  },
  {
    id: 3,
    code: "002",
    name: "Fortune General Insurance",
    branch: "Cebu Branch",
    address: "45 Colon St, Cebu City",
    contact: "032-8123-4567",
    email: "cebu@fortune.com",
    manager: "Pedro Reyes",
    status: "Active",
    dateCreated: "Feb 20, 2026",
    vouchers: 890,
  },
  {
    id: 4,
    code: "002",
    name: "Fortune General Insurance",
    branch: "Mandaue Branch",
    address: "Mandaue City, Cebu",
    contact: "032-8456-7890",
    email: "mandaue@fortune.com",
    manager: "Ana Lim",
    status: "Inactive",
    dateCreated: "Mar 5, 2026",
    vouchers: 320,
  },
  {
    id: 5,
    code: "003",
    name: "Malayan Insurance Co.",
    branch: "Davao Branch",
    address: "78 JP Laurel Ave, Davao City",
    contact: "082-8123-4567",
    email: "davao@malayan.com",
    manager: "Jose Bautista",
    status: "Active",
    dateCreated: "Jan 8, 2026",
    vouchers: 2100,
  },
  {
    id: 6,
    code: "003",
    name: "Malayan Insurance Co.",
    branch: "GenSan Branch",
    address: "General Santos City",
    contact: "083-8123-4567",
    email: "gensan@malayan.com",
    manager: "Carla Torres",
    status: "Active",
    dateCreated: "Mar 20, 2026",
    vouchers: 780,
  },
  {
    id: 7,
    code: "004",
    name: "Country Bankers Insurance",
    branch: "BGC Branch",
    address: "11th Ave, BGC, Taguig",
    contact: "02-8456-7890",
    email: "bgc@countrybankers.com",
    manager: "Ramon Garcia",
    status: "Inactive",
    dateCreated: "Dec 1, 2023",
    vouchers: 450,
  },
  {
    id: 8,
    code: "005",
    name: "Standard Insurance Co.",
    branch: "QC Branch",
    address: "12 Quezon Ave, QC",
    contact: "02-8789-0123",
    email: "qc@standard.com",
    manager: "Luz Fernandez",
    status: "Inactive",
    dateCreated: "Mar 10, 2026",
    vouchers: 1560,
  },
  {
    id: 9,
    code: "006",
    name: "Charter Ping An Insurance",
    branch: "Ortigas Branch",
    address: "ADB Ave, Mandaluyong",
    contact: "02-8901-2345",
    email: "ortigas@charterpingan.com",
    manager: "Ricardo Gomez",
    status: "Deactivated",
    dateCreated: "Nov 15, 2023",
    vouchers: 0,
  },
  {
    id: 10,
    code: "007",
    name: "BPI MS Insurance",
    branch: "Makati Branch",
    address: "6750 Ayala Ave, Makati",
    contact: "02-8812-3456",
    email: "makati@bpims.com",
    manager: "Isabella Cruz",
    status: "Active",
    dateCreated: "Apr 5, 2026",
    vouchers: 3200,
  },
  {
    id: 11,
    code: "007",
    name: "BPI MS Insurance",
    branch: "Alabang Branch",
    address: "Alabang, Muntinlupa",
    contact: "02-8812-7890",
    email: "alabang@bpims.com",
    manager: "Francisco Lopez",
    status: "Active",
    dateCreated: "Apr 15, 2026",
    vouchers: 890,
  },
  {
    id: 12,
    code: "008",
    name: "AXA Philippines",
    branch: "BGC Branch",
    address: "Bonifacio Global City",
    contact: "02-8123-4567",
    email: "bgc@axa.com.ph",
    manager: "Maria Santos",
    status: "Active",
    dateCreated: "Mar 20, 2026",
    vouchers: 1870,
  },
];
