// src/constants/companyMockData.js

export const MOCK_COMPANIES = [
  {
    id: 1,
    code: "001",
    name: "Premier Insurance Corp",
    provider: "LTO",
    vouchers: 1250,
    status: "Active",
    dateCreated: "Jan 15, 2026",
    branch: "Main Branch",
    address: "123 Ayala Ave, Makati City",
    contact: "02-8123-4567",
    email: "info@premier.com",
  },
  {
    id: 2,
    code: "002",
    name: "Fortune General Insurance",
    provider: "LTO",
    vouchers: 890,
    status: "Active",
    dateCreated: "Feb 20, 2026",
    branch: "Cebu Branch",
    address: "45 Colon St, Cebu City",
    contact: "032-8123-4567",
    email: "info@fortune.com",
  },
  {
    id: 3,
    code: "003",
    name: "Malayan Insurance Co.",
    provider: "LTO",
    vouchers: 2100,
    status: "Active",
    dateCreated: "Jan 8, 2026",
    branch: "Davao Branch",
    address: "78 JP Laurel Ave, Davao City",
    contact: "082-8123-4567",
    email: "info@malayan.com",
  },
  {
    id: 4,
    code: "004",
    name: "Country Bankers Insurance",
    provider: "LTO",
    vouchers: 450,
    status: "Inactive",
    dateCreated: "Dec 1, 2023",
    branch: "BGC Branch",
    address: "11th Ave, BGC, Taguig",
    contact: "02-8456-7890",
    email: "info@countrybankers.com",
  },
  {
    id: 5,
    code: "005",
    name: "Standard Insurance Co.",
    provider: "LTO",
    vouchers: 1560,
    status: "Inactive",
    dateCreated: "Mar 10, 2026",
    branch: "QC Branch",
    address: "12 Quezon Ave, QC",
    contact: "02-8789-0123",
    email: "info@standard.com",
  },
  {
    id: 6,
    code: "006",
    name: "Charter Ping An Insurance",
    provider: "LTO",
    vouchers: 0,
    status: "Deactivated",
    dateCreated: "Nov 15, 2023",
    branch: "Ortigas Branch",
    address: "ADB Ave, Mandaluyong",
    contact: "02-8901-2345",
    email: "info@charterpingan.com",
  },
  {
    id: 7,
    code: "007",
    name: "BPI MS Insurance",
    provider: "LTO",
    vouchers: 3200,
    status: "Active",
    dateCreated: "Apr 5, 2026",
    branch: "Makati Branch",
    address: "6750 Ayala Ave, Makati",
    contact: "02-8812-3456",
    email: "info@bpims.com",
  },
  {
    id: 8,
    code: "008",
    name: "AXA Philippines",
    provider: "LTO",
    vouchers: 1870,
    status: "Active",
    dateCreated: "Mar 20, 2026",
    branch: "BGC Branch",
    address: "Bonifacio Global City",
    contact: "02-8123-4567",
    email: "info@axa.com.ph",
  },
  {
    id: 9,
    code: "009",
    name: "Pru Life UK",
    provider: "LTO",
    vouchers: 950,
    status: "Inactive",
    dateCreated: "Feb 1, 2026",
    branch: "Ortigas Branch",
    address: "Ortigas Center, Pasig",
    contact: "02-8123-4567",
    email: "info@prulifeuk.com",
  },
  {
    id: 10,
    code: "010",
    name: "FWD Insurance",
    provider: "LTO",
    vouchers: 620,
    status: "Active",
    dateCreated: "Jan 25, 2026",
    branch: "BGC Branch",
    address: "BGC, Taguig",
    contact: "02-8123-4567",
    email: "info@fwd.com.ph",
  },
];
