// src/constants/companyMockData.js

export const MOCK_COMPANIES = [
  {
    id: 1,
    code: "001",
    name: "Premier Insurance Corp",
    provider: "LTO",
    vouchers: 1250,
    status: "Active",
    dateCreated: "Jan 15, 2026",
    address: "123 Ayala Ave, Makati City",
    contact: "02-8123-4567",
  },
  {
    id: 2,
    code: "002",
    name: "Fortune General Insurance",
    provider: "LTO",
    vouchers: 890,
    status: "Active",
    dateCreated: "Feb 20, 2026",
    address: "45 Colon St, Cebu City",
    contact: "032-8123-4567",
  },
  {
    id: 3,
    code: "003",
    name: "Malayan Insurance Co.",
    provider: "LTO",
    vouchers: 2100,
    status: "Active",
    dateCreated: "Jan 8, 2026",
    address: "78 JP Laurel Ave, Davao City",
    contact: "082-8123-4567",
  },
  {
    id: 4,
    code: "004",
    name: "Country Bankers Insurance",
    provider: "LTO",
    vouchers: 450,
    status: "Inactive",
    dateCreated: "Dec 1, 2023",
    address: "11th Ave, BGC, Taguig",
    contact: "02-8456-7890",
  },
  {
    id: 5,
    code: "005",
    name: "Standard Insurance Co.",
    provider: "LTO",
    vouchers: 1560,
    status: "Inactive",
    dateCreated: "Mar 10, 2026",
    address: "12 Quezon Ave, QC",
    contact: "02-8789-0123",
  },
  {
    id: 6,
    code: "006",
    name: "Charter Ping An Insurance",
    provider: "LTO",
    vouchers: 0,
    status: "Deactivated",
    dateCreated: "Nov 15, 2023",
    address: "ADB Ave, Mandaluyong",
    contact: "02-8901-2345",
  },
];

export const MOCK_BRANCHES = [
  {
    id: 1,
    code: "001",
    name: "Premier Insurance Corp",
    branch: "Main Branch",
    address: "123 Ayala Ave, Makati City",
    contact: "02-8123-4567",
    manager: "Juan Dela Cruz",
    status: "Active",
    dateCreated: "Jan 15, 2026",
    vouchers: 1250,
  },
  {
    id: 2,
    code: "001",
    name: "Premier Insurance Corp",
    branch: "North Edsa Branch",
    address: "North Edsa, Quezon City",
    contact: "02-8456-7890",
    manager: "Maria Santos",
    status: "Active",
    dateCreated: "Feb 10, 2026",
    vouchers: 450,
  },
  {
    id: 3,
    code: "002",
    name: "Fortune General Insurance",
    branch: "Cebu Branch",
    address: "45 Colon St, Cebu City",
    contact: "032-8123-4567",
    manager: "Pedro Reyes",
    status: "Active",
    dateCreated: "Feb 20, 2026",
    vouchers: 890,
  },
  {
    id: 4,
    code: "002",
    name: "Fortune General Insurance",
    branch: "Mandaue Branch",
    address: "Mandaue City, Cebu",
    contact: "032-8456-7890",
    manager: "Ana Lim",
    status: "Inactive",
    dateCreated: "Mar 5, 2026",
    vouchers: 320,
  },
  {
    id: 5,
    code: "003",
    name: "Malayan Insurance Co.",
    branch: "Davao Branch",
    address: "78 JP Laurel Ave, Davao City",
    contact: "082-8123-4567",
    manager: "Jose Bautista",
    status: "Active",
    dateCreated: "Jan 8, 2026",
    vouchers: 2100,
  },
];
