// src/constants/mockData.js

export const MOCK_ASSIGNED_VOUCHERS = [
  {
    id: 1,
    voucherCode: "VCH-ABC123XYZ",
    productName: "BASIC CTPL",
    premium: 60.0,
    assignedBy: "Juan Dela Cruz",
    assignedDate: "May 15, 2026",
    expiryDate: "May 15, 2027",
    status: "Active",
  },
  {
    id: 2,
    voucherCode: "VCH-DEF456UVW",
    productName: "BASIC CTPL",
    premium: 60.0,
    assignedBy: "Maria Santos",
    assignedDate: "May 10, 2026",
    expiryDate: "May 10, 2027",
    status: "Active",
  },
  {
    id: 3,
    voucherCode: "VCH-GHI789RST",
    productName: "BASIC CTPL",
    premium: 60.0,
    assignedBy: "Pedro Reyes",
    assignedDate: "May 5, 2026",
    expiryDate: "Nov 5, 2026",
    status: "Active",
  },
  {
    id: 4,
    voucherCode: "VCH-JKL012MNO",
    productName: "BASIC CTPL",
    premium: 60.0,
    assignedBy: "Juan Dela Cruz",
    assignedDate: "Apr 28, 2026",
    expiryDate: "Apr 28, 2027",
    status: "Used",
  },
  {
    id: 5,
    voucherCode: "VCH-PQR345STU",
    productName: "BASIC CTPL",
    premium: 60.0,
    assignedBy: "Maria Santos",
    assignedDate: "Apr 20, 2026",
    expiryDate: "Apr 20, 2027",
    status: "Expired",
  },
];

export const MOCK_PRODUCTS = [
  {
    id: 1,
    productName: "BASIC CTPL",
    coverage: "Third Party Liability",
    price: 60.0,
    description:
      "Compulsory Third Party Liability insurance for LTO vehicle registration",
    validityDays: 365,
    insuranceCode: "PRIVATE CARS (INCLUDING JEEPS AND AUVS)",
    isActive: true,
  },
];

export const MOCK_PURCHASE_HISTORY = [
  {
    id: "POL-20241201-001",
    policyNumber: "CTPL-2024-123456",
    voucherCode: "VCH-ABC123XYZ",
    productName: "BASIC CTPL",
    premium: 60.0,
    purchaseDate: "Dec 1, 2024",
    expirationDate: "Dec 1, 2025",
    status: "Active",
    redeemedOn: null,
    insuranceCode: "PRIVATE CARS (INCLUDING JEEPS AND AUVS)",
  },
  {
    id: "POL-20241125-002",
    policyNumber: "CTPL-2024-789012",
    voucherCode: "VCH-DEF456UVW",
    productName: "BASIC CTPL",
    premium: 60.0,
    purchaseDate: "Nov 25, 2024",
    expirationDate: "Nov 25, 2025",
    status: "Redeemed",
    redeemedOn: "Nov 26, 2024",
    insuranceCode: "PRIVATE CARS (INCLUDING JEEPS AND AUVS)",
  },
  {
    id: "POL-20241015-003",
    policyNumber: "CTPL-2024-345678",
    voucherCode: "VCH-GHI789RST",
    productName: "BASIC CTPL",
    premium: 60.0,
    purchaseDate: "Oct 15, 2024",
    expirationDate: "Apr 15, 2025",
    status: "Expired",
    redeemedOn: null,
    insuranceCode: "MOTORCYCLES",
  },
];

export const MOCK_COMPANIES = [
  {
    id: 1,
    code: "PIC-001",
    name: "ALPHA INSURANCE AND SURETY COMPANY INC.",
    provider: "LTO",
    status: "Active",
    dateCreated: "2026-01-15",
    branch: "MANILA",
    address: "123 Ayala Ave, Makati City",
    logo: null,
  },
  {
    id: 2,
    code: "FGI-002",
    name: "Fortune General Insurance",
    provider: "LTO",
    status: "Pending",
    dateCreated: "2026-02-20",
    branch: "Cebu Branch",
    address: "45 Colon St, Cebu City",
    logo: null,
  },
  {
    id: 3,
    code: "MIC-003",
    name: "Malayan Insurance Co.",
    provider: "LTO",
    status: "Active",
    dateCreated: "2026-01-08",
    branch: "Davao",
    address: "78 JP Laurel Ave, Davao City",
    logo: null,
  },
  {
    id: 4,
    code: "COC-004",
    name: "Country Bankers Insurance",
    provider: "LTO",
    status: "Inactive",
    dateCreated: "2023-12-01",
    branch: "BGC",
    address: "11th Ave, BGC, Taguig",
    logo: null,
  },
  {
    id: 5,
    code: "SGI-005",
    name: "Standard Insurance Co.",
    provider: "LTO",
    status: "Declined",
    dateCreated: "2026-03-10",
    branch: "QC Branch",
    address: "12 Quezon Ave, QC",
    logo: null,
  },
  {
    id: 6,
    code: "CAI-006",
    name: "Charter Ping An Insurance",
    provider: "LTO",
    status: "Deactivated",
    dateCreated: "2023-11-15",
    branch: "Ortigas",
    address: "ADB Ave, Mandaluyong",
    logo: null,
  },
];

// UPDATED TRANSACTIONS with ONLY Web origin
export const MOCK_TRANSACTIONS = [
  {
    id: 1,
    account: "Juan Dela Cruz",
    company: "ALPHA INSURANCE AND SURETY COMPANY INC. - MANILA",
    refNo: "R123456VLQQIS7FHOX8O",
    description: "SUBMIT VEHICLE WITH THE FOLLOWING RN#123456ABCDEFGHIJKLMN",
    response:
      "SUCCESSFULLY AUTHENTICATED USING AUTHENTICATION CODE #R123-5456K-R7QN-UVZV",
    origin: "Web",
    status: "Authenticated",
    dateCreated: "May 27, 2026 10:16 AM",
  },
  {
    id: 2,
    account: "Juan Dela Cruz",
    company: "ALPHA INSURANCE AND SURETY COMPANY INC. - MANILA",
    refNo: "R123456VLQQIS7FHOX8O",
    description: "INITIATED VEHICLE VERIFICATION VIA WEB (PLATE NO: LAJ1234)",
    response: "VEHICLE HAS BEEN VERIFIED",
    origin: "Web",
    status: "Verified",
    dateCreated: "May 27, 2026 10:16 AM",
  },
  // FAILED Scenario 1: Vehicle Not Found
  {
    id: 3,
    account: "Juan Dela Cruz",
    company: "ALPHA INSURANCE AND SURETY COMPANY INC. - MANILA",
    refNo: "R123456VLQQIS7FHOX8O",
    description: "INITIATED VEHICLE VERIFICATION VIA WEB (PLATE NO: LAJ1234)",
    response: "VEHICLE NOT FOUND!",
    origin: "Web",
    status: "Failed",
    dateCreated: "May 27, 2026 10:16 AM",
  },

  // FAILED Scenario 2: Already Verified
  {
    id: 4,
    account: "Maria Santos",
    company: "ALPHA INSURANCE AND SURETY COMPANY INC. - MANILA",
    refNo: "R987654ABCDEFGHIJKLM",
    description: "INITIATED VEHICLE VERIFICATION VIA WEB (PLATE NO: XYZ5678)",
    response:
      "THIS VEHICLE HAS ALREADY BEEN VERIFIED AND HAS AN EXISTING CERTIFICATE.",
    origin: "Web",
    status: "Failed",
    dateCreated: "May 26, 2026 02:30 PM",
  },
  {
    id: 5,
    account: "Maria Santos",
    company: "ALPHA INSURANCE AND SURETY COMPANY INC. - MANILA",
    refNo: "R987654ABCDEFGHIJKLM",
    description: "INITIATED VEHICLE VERIFICATION VIA WEB (PLATE NO: XYZ5678)",
    response: "VEHICLE HAS BEEN VERIFIED",
    origin: "Web",
    status: "Verified",
    dateCreated: "May 26, 2026 02:35 PM",
  },
  {
    id: 6,
    account: "Pedro Reyes",
    company: "Fortune General Insurance - Cebu Branch",
    refNo: "R456789MNOPQRSTUVWX",
    description: "SUBMIT VEHICLE WITH THE FOLLOWING RN#456789ABCDEFGHIJKL",
    response:
      "SUCCESSFULLY AUTHENTICATED USING AUTHENTICATION CODE #P456-7890B-C1D2-E3F4",
    origin: "Web",
    status: "Authenticated",
    dateCreated: "May 25, 2026 09:15 AM",
  },
  {
    id: 7,
    account: "Pedro Reyes",
    company: "Fortune General Insurance - Cebu Branch",
    refNo: "R456789MNOPQRSTUVWX",
    description: "INITIATED VEHICLE VERIFICATION VIA WEB (PLATE NO: CEB1234)",
    response: "VEHICLE HAS BEEN VERIFIED",
    origin: "Web",
    status: "Verified",
    dateCreated: "May 25, 2026 09:20 AM",
  },
  {
    id: 8,
    account: "Ana Lim",
    company: "Malayan Insurance Co. - Davao",
    refNo: "R321654ZYXWVUTSRQPO",
    description: "SUBMIT VEHICLE WITH THE FOLLOWING RN#321654ABCDEFGHIJKL",
    response:
      "SUCCESSFULLY AUTHENTICATED USING AUTHENTICATION CODE #A321-6543C-D4E5-F6G7",
    origin: "Web",
    status: "Authenticated",
    dateCreated: "May 24, 2026 11:00 AM",
  },
  {
    id: 9,
    account: "Ana Lim",
    company: "Malayan Insurance Co. - Davao",
    refNo: "R321654ZYXWVUTSRQPO",
    description: "INITIATED VEHICLE VERIFICATION VIA WEB (PLATE NO: DVO7890)",
    response: "- VEHICLE NOT FOUND!\n- INVALID PLATE NUMBER FORMAT.",
    origin: "Web",
    status: "Failed",
    dateCreated: "May 24, 2026 11:05 AM",
  },
  {
    id: 10,
    account: "Jose Bautista",
    company: "Standard Insurance Co. - QC Branch",
    refNo: "R741852QWERTYUIOPAS",
    description: "SUBMIT VEHICLE WITH THE FOLLOWING RN#741852ABCDEFGHIJKL",
    response:
      "SUCCESSFULLY AUTHENTICATED USING AUTHENTICATION CODE #J741-8523D-E5F6-G7H8",
    origin: "Web",
    status: "Authenticated",
    dateCreated: "May 23, 2026 03:45 PM",
  },
];

export const MOCK_VEHICLE = {
  plateNumber: "ABC 1234",
  mvFileNo: "MV-2019-00456789",
  engineNo: "4K-E123456",
  chassisNo: "JTDBE33K7Y0123456",
  makeModel: "Toyota Vios 1.3 E",
  yearModel: "2019",
  color: "Pearl White",
  bodyType: "Sedan",
  fuelType: "Gasoline",
  grossWeight: "1,405 kg",
  netWeight: "1,155 kg",
  mvType: "Private",
  orcrNo: "OR-2023-78901",
  registrationExpiry: "December 31, 2026",
};

export const MOCK_OWNER = {
  lastName: "Dela Cruz",
  firstName: "Juan",
  middleName: "Santos",
  address: "123 Rizal St, San Juan, Metro Manila",
  zipCode: "1500",
  contactNo: "09171234567",
  email: "juan.delacruz@email.com",
  tin: "123-456-789-000",
};

export const MOCK_INSURANCE = {
  insurer: "ALPHA INSURANCE AND SURETY COMPANY INC.",
  policyNo: "POL-CTPL-2026-00789",
  effectivityDate: "January 1, 2026",
  expiryDate: "December 31, 2026",
  coverageType: "CTPL - Compulsory Third Party Liability",
  sumInsured: "₱ 100,000.00",
  premium: "₱ 60.00",
  agentName: "Juan Dela Cruz",
};

export const MOCK_DATA = {
  assignedVouchers: MOCK_ASSIGNED_VOUCHERS,
  products: MOCK_PRODUCTS,
  purchaseHistory: MOCK_PURCHASE_HISTORY,
  companies: MOCK_COMPANIES,
  transactions: MOCK_TRANSACTIONS,
  vehicle: MOCK_VEHICLE,
  owner: MOCK_OWNER,
  insurance: MOCK_INSURANCE,
};

export const MOCK_USERS = [
  {
    id: 1,
    name: "Juan Dela Cruz",
    company: "ALPHA INSURANCE AND SURETY COMPANY INC.",
    branch: "MANILA",
    role: "Manager",
    vouchers: 45,
    status: "Active",
    dateCreated: "Jan 15, 2026",
    email: "juan.delacruz@alpha.com",
    phone: "09171234567",
  },
  {
    id: 2,
    name: "Maria Santos",
    company: "ALPHA INSURANCE AND SURETY COMPANY INC.",
    branch: "MANILA",
    role: "Agent",
    vouchers: 12,
    status: "Active",
    dateCreated: "Feb 10, 2026",
    email: "maria.santos@alpha.com",
    phone: "09171234568",
  },
  {
    id: 3,
    name: "Pedro Reyes",
    company: "Fortune General Insurance",
    branch: "Cebu Branch",
    role: "Agent",
    vouchers: 8,
    status: "Active",
    dateCreated: "Mar 5, 2026",
    email: "pedro.reyes@fortune.com",
    phone: "09171234569",
  },
  {
    id: 4,
    name: "Ana Lim",
    company: "Malayan Insurance Co.",
    branch: "Davao",
    role: "Agent",
    vouchers: 15,
    status: "Active",
    dateCreated: "Feb 28, 2026",
    email: "ana.lim@malayan.com",
    phone: "09171234570",
  },
  {
    id: 5,
    name: "Jose Bautista",
    company: "Standard Insurance Co.",
    branch: "QC Branch",
    role: "Agent",
    vouchers: 6,
    status: "Active",
    dateCreated: "Mar 15, 2026",
    email: "jose.bautista@standard.com",
    phone: "09171234571",
  },
];
