// constants/mockActivityLogs.js
export const MOCK_ACTIVITY_LOGS = [
  {
    id: 1,
    user: "John Admin",
    role: "Admin",
    action: "CREATE",
    details: "Created new user account for Jane Agent",
    timestamp: "2024-01-15 09:30:00",
  },
  {
    id: 2,
    user: "Sarah Manager",
    role: "Manager",
    action: "UPDATE",
    details: "Updated company information and contact details",
    timestamp: "2024-01-15 10:15:00",
  },
  {
    id: 3,
    user: "Mike Agent",
    role: "Agent",
    action: "VERIFY",
    details: "Verified vehicle with plate number ABC-1234",
    timestamp: "2024-01-15 11:00:00",
  },
  {
    id: 4,
    user: "John Admin",
    role: "Admin",
    action: "DELETE",
    details: "Deleted branch North Branch from system",
    timestamp: "2024-01-15 11:30:00",
  },
  {
    id: 5,
    user: "Sarah Manager",
    role: "Manager",
    action: "ASSIGN",
    details: "Assigned 50 vouchers to agent Mike Agent",
    timestamp: "2024-01-15 13:45:00",
  },
  {
    id: 6,
    user: "Jane Agent",
    role: "Agent",
    action: "GENERATE",
    details: "Generated certificate for vehicle XYZ-5678",
    timestamp: "2024-01-15 14:20:00",
  },
  {
    id: 7,
    user: "John Admin",
    role: "Admin",
    action: "UPDATE",
    details: "Changed company status from Active to Inactive",
    timestamp: "2024-01-15 15:00:00",
  },
  {
    id: 8,
    user: "Sarah Manager",
    role: "Manager",
    action: "TRANSFER",
    details: "Transferred 25 vouchers from Jane to Mike",
    timestamp: "2024-01-15 15:30:00",
  },
  {
    id: 9,
    user: "Mike Agent",
    role: "Agent",
    action: "LOGIN",
    details: "Successful login from new device",
    timestamp: "2024-01-15 16:00:00",
  },
  {
    id: 10,
    user: "John Admin",
    role: "Admin",
    action: "CREATE",
    details: "Created new branch South Branch",
    timestamp: "2024-01-15 16:45:00",
  },
  {
    id: 11,
    user: "Jane Agent",
    role: "Agent",
    action: "VERIFY",
    details: "Verified vehicle with plate number XYZ-7890",
    timestamp: "2024-01-16 09:00:00",
  },
  {
    id: 12,
    user: "Mike Agent",
    role: "Agent",
    action: "GENERATE",
    details: "Generated certificate for vehicle DEF-4567",
    timestamp: "2024-01-16 10:30:00",
  },
];
