// src/constants/mockData.js

export const MOCK_ASSIGNED_VOUCHERS = [
  {
    id: 1,
    voucherCode: "VCH-ABC123XYZ",
    productName: "BASIC CTPL",
    premium: 60.0, // Changed from 560 to 60
    assignedBy: "Juan Dela Cruz",
    assignedDate: "May 15, 2026",
    expiryDate: "May 15, 2027",
    status: "Active",
  },
  {
    id: 2,
    voucherCode: "VCH-DEF456UVW",
    productName: "BASIC CTPL",
    premium: 60.0, // Changed from 850 to 60
    assignedBy: "Maria Santos",
    assignedDate: "May 10, 2026",
    expiryDate: "May 10, 2027",
    status: "Active",
  },
  {
    id: 3,
    voucherCode: "VCH-GHI789RST",
    productName: "BASIC CTPL",
    premium: 60.0, // Changed from 350 to 60
    assignedBy: "Pedro Reyes",
    assignedDate: "May 5, 2026",
    expiryDate: "Nov 5, 2026",
    status: "Active",
  },
  {
    id: 4,
    voucherCode: "VCH-JKL012MNO",
    productName: "BASIC CTPL",
    premium: 60.0, // Changed from 1200 to 60
    assignedBy: "Juan Dela Cruz",
    assignedDate: "Apr 28, 2026",
    expiryDate: "Apr 28, 2027",
    status: "Used",
  },
  {
    id: 5,
    voucherCode: "VCH-PQR345STU",
    productName: "BASIC CTPL",
    premium: 60.0, // Changed from 1800 to 60
    assignedBy: "Maria Santos",
    assignedDate: "Apr 20, 2026",
    expiryDate: "Apr 20, 2027",
    status: "Expired",
  },
];

export const MOCK_PRODUCTS = [
  {
    id: 1,
    productName: "Basic CTPL",
    coverage: "Third Party Liability",
    price: 60.0, // Changed from 560.00 to 60.00
    description: "Basic coverage for third party liability as required by LTO",
    validityDays: 365,
    insuranceCode: "PRIVATE CARS (INCLUDING JEEPS AND AUVS)",
    isActive: true,
  },
];

export const MOCK_PURCHASE_HISTORY = [
  {
    id: "POL-20241201-001",
    policyNumber: "CTPL-2024-123456",
    voucherCode: "VCH-ABC123XYZ",
    productName: "Basic CTPL",
    premium: 560.0,
    purchaseDate: "Dec 1, 2024",
    expirationDate: "Dec 1, 2025",
    status: "Active",
    redeemedOn: null,
    insuranceCode: "PRIVATE CARS (INCLUDING JEEPS AND AUVS)",
  },
  {
    id: "POL-20241125-002",
    policyNumber: "CTPL-2024-789012",
    voucherCode: "VCH-DEF456UVW",
    productName: "Premium CTPL",
    premium: 850.0,
    purchaseDate: "Nov 25, 2024",
    expirationDate: "Nov 25, 2025",
    status: "Redeemed",
    redeemedOn: "Nov 26, 2024",
    insuranceCode: "PRIVATE CARS (INCLUDING JEEPS AND AUVS)",
  },
  {
    id: "POL-20241015-003",
    policyNumber: "CTPL-2024-345678",
    voucherCode: "VCH-GHI789RST",
    productName: "Motorcycle CTPL",
    premium: 350.0,
    purchaseDate: "Oct 15, 2024",
    expirationDate: "Apr 15, 2025",
    status: "Expired",
    redeemedOn: null,
    insuranceCode: "MOTORCYCLES",
  },
];

export const MOCK_COMPANIES = [
  {
    id: 1,
    code: "PIC-001",
    name: "Premier Insurance Corp",
    provider: "LTO",
    status: "Active",
    dateCreated: "2026-01-15",
    branch: "Main",
    address: "123 Ayala Ave, Makati City",
    logo: null,
  },
  {
    id: 2,
    code: "FGI-002",
    name: "Fortune General Insurance",
    provider: "LTO",
    status: "Pending",
    dateCreated: "2026-02-20",
    branch: "Cebu Branch",
    address: "45 Colon St, Cebu City",
    logo: null,
  },
  {
    id: 3,
    code: "MIC-003",
    name: "Malayan Insurance Co.",
    provider: "LTO",
    status: "Active",
    dateCreated: "2026-01-08",
    branch: "Davao",
    address: "78 JP Laurel Ave, Davao City",
    logo: null,
  },
  {
    id: 4,
    code: "COC-004",
    name: "Country Bankers Insurance",
    provider: "LTO",
    status: "Inactive",
    dateCreated: "2023-12-01",
    branch: "BGC",
    address: "11th Ave, BGC, Taguig",
    logo: null,
  },
  {
    id: 5,
    code: "SGI-005",
    name: "Standard Insurance Co.",
    provider: "LTO",
    status: "Declined",
    dateCreated: "2026-03-10",
    branch: "QC Branch",
    address: "12 Quezon Ave, QC",
    logo: null,
  },
  {
    id: 6,
    code: "CAI-006",
    name: "Charter Ping An Insurance",
    provider: "LTO",
    status: "Deactivated",
    dateCreated: "2023-11-15",
    branch: "Ortigas",
    address: "ADB Ave, Mandaluyong",
    logo: null,
  },
];

export const MOCK_TRANSACTIONS = [
  {
    id: 1,
    account: "Juan Dela Cruz",
    company: "Premier Insurance Corp",
    refNo: "TXN-20260115-001",
    description: "Initiated vehicle verification via web (Plate ABC 1234)",
    response: "Vehicle has been verified successfully",
    origin: "web",
    status: "Authenticated",
    dateCreated: "Jan 15, 2026 09:14:32",
  },
  {
    id: 2,
    account: "Maria Santos",
    company: "Premier Insurance Corp",
    refNo: "TXN-20260115-002",
    description: "Verified vehicle documents for MV File No. MV-2019-00456789",
    response: "Documents verified and approved",
    origin: "web",
    status: "Verified",
    dateCreated: "Jan 15, 2026 09:45:11",
  },
  {
    id: 3,
    account: "Pedro Reyes",
    company: "Fortune General Insurance",
    refNo: "TXN-20260115-003",
    description:
      "Initiated vehicle verification via mobile app (Plate XYZ 5678)",
    response: "Vehicle not found in database",
    origin: "mobile",
    status: "Failed",
    dateCreated: "Jan 15, 2026 10:02:47",
  },
  {
    id: 4,
    account: "Ana Lim",
    company: "Fortune General Insurance",
    refNo: "TXN-20260115-004",
    description: "Verified vehicle ownership documents",
    response: "Ownership confirmed - Certificate issued",
    origin: "web",
    status: "Authenticated",
    dateCreated: "Jan 15, 2026 10:30:05",
  },
  {
    id: 5,
    account: "Jose Bautista",
    company: "Malayan Insurance Co.",
    refNo: "TXN-20260115-005",
    description: "API call for vehicle verification (Engine No. 4K-E123456)",
    response: "Vehicle has been verified",
    origin: "api",
    status: "Verified",
    dateCreated: "Jan 15, 2026 11:00:22",
  },
  {
    id: 6,
    account: "Carla Torres",
    company: "Standard Insurance Co.",
    refNo: "TXN-20260115-006",
    description:
      "Initiated vehicle verification via web (Chassis No. JTDBE33K7Y0123456)",
    response: "Verification failed - Invalid chassis number",
    origin: "web",
    status: "Failed",
    dateCreated: "Jan 15, 2026 11:30:45",
  },
  {
    id: 7,
    account: "Ramon Garcia",
    company: "Standard Insurance Co.",
    refNo: "TXN-20260115-007",
    description: "Verified vehicle LTO registration status",
    response: "Registration is active and valid",
    origin: "web",
    status: "Authenticated",
    dateCreated: "Jan 15, 2026 12:15:33",
  },
  {
    id: 8,
    account: "Luz Fernandez",
    company: "Premier Insurance Corp",
    refNo: "TXN-20260115-008",
    description: "Mobile app verification for Plate ABC 1234",
    response: "Vehicle has been verified",
    origin: "mobile",
    status: "Verified",
    dateCreated: "Jan 15, 2026 13:00:18",
  },
  {
    id: 9,
    account: "Ricardo Gomez",
    company: "Malayan Insurance Co.",
    refNo: "TXN-20260115-009",
    description: "API batch verification request",
    response: "Partial success - 3 vehicles verified",
    origin: "api",
    status: "Authenticated",
    dateCreated: "Jan 15, 2026 14:20:55",
  },
  {
    id: 10,
    account: "Isabella Cruz",
    company: "Charter Ping An Insurance",
    refNo: "TXN-20260115-010",
    description: "Web verification for MV File No. MV-2020-00890123",
    response: "Verification failed - Expired registration",
    origin: "web",
    status: "Failed",
    dateCreated: "Jan 15, 2026 15:45:22",
  },
];

export const MOCK_VEHICLE = {
  plateNumber: "ABC 1234",
  mvFileNo: "MV-2019-00456789",
  engineNo: "4K-E123456",
  chassisNo: "JTDBE33K7Y0123456",
  makeModel: "Toyota Vios 1.3 E",
  yearModel: "2019",
  color: "Pearl White",
  bodyType: "Sedan",
  fuelType: "Gasoline",
  grossWeight: "1,405 kg",
  netWeight: "1,155 kg",
  mvType: "Private",
  orcrNo: "OR-2023-78901",
  registrationExpiry: "December 31, 2026",
};

export const MOCK_OWNER = {
  lastName: "Dela Cruz",
  firstName: "Juan",
  middleName: "Santos",
  address: "123 Rizal St, San Juan, Metro Manila",
  zipCode: "1500",
  contactNo: "09171234567",
  email: "juan.delacruz@email.com",
  tin: "123-456-789-000",
};

export const MOCK_INSURANCE = {
  insurer: "Premier Insurance Corp.",
  policyNo: "POL-CTPL-2026-00789",
  effectivityDate: "January 1, 2026",
  expiryDate: "December 31, 2026",
  coverageType: "CTPL - Compulsory Third Party Liability",
  sumInsured: "₱ 100,000.00",
  premium: "₱ 650.00",
  agentName: "Maria Santos",
};

// Optional: Export all as a single object for convenience
export const MOCK_DATA = {
  assignedVouchers: MOCK_ASSIGNED_VOUCHERS,
  products: MOCK_PRODUCTS,
  purchaseHistory: MOCK_PURCHASE_HISTORY,
  companies: MOCK_COMPANIES,
  transactions: MOCK_TRANSACTIONS,
  vehicle: MOCK_VEHICLE,
  owner: MOCK_OWNER,
  insurance: MOCK_INSURANCE,
};

// Add this to your src/constants/mockData.js

export const MOCK_USERS = [
  {
    id: 1,
    name: "Juan Dela Cruz",
    company: "Premier Insurance Corp",
    branch: "Main Branch",
    role: "Manager",
    vouchers: 45,
    status: "Active",
    dateCreated: "Jan 15, 2026",
    email: "juan.delacruz@premier.com",
    phone: "09171234567",
  },
  {
    id: 2,
    name: "Maria Santos",
    company: "Premier Insurance Corp",
    branch: "Main Branch",
    role: "Agent",
    vouchers: 12,
    status: "Active",
    dateCreated: "Feb 10, 2026",
    email: "maria.santos@premier.com",
    phone: "09171234568",
  },
  {
    id: 3,
    name: "Pedro Reyes",
    company: "Fortune General Insurance",
    branch: "Cebu Branch",
    role: "Agent",
    vouchers: 8,
    status: "Active",
    dateCreated: "Mar 5, 2026",
    email: "pedro.reyes@fortune.com",
    phone: "09171234569",
  },
  {
    id: 4,
    name: "Ana Lim",
    company: "Fortune General Insurance",
    branch: "Cebu Branch",
    role: "Sub Agent",
    vouchers: 3,
    status: "Inactive",
    dateCreated: "Jan 20, 2026",
    email: "ana.lim@fortune.com",
    phone: "09171234570",
  },
  {
    id: 5,
    name: "Jose Bautista",
    company: "Malayan Insurance Co.",
    branch: "Davao Branch",
    role: "Manager",
    vouchers: 32,
    status: "Active",
    dateCreated: "Dec 10, 2025",
    email: "jose.bautista@malayan.com",
    phone: "09171234571",
  },
  {
    id: 6,
    name: "Carla Torres",
    company: "Malayan Insurance Co.",
    branch: "Davao Branch",
    role: "Agent",
    vouchers: 15,
    status: "Active",
    dateCreated: "Feb 28, 2026",
    email: "carla.torres@malayan.com",
    phone: "09171234572",
  },
  {
    id: 7,
    name: "Ramon Garcia",
    company: "Standard Insurance Co.",
    branch: "QC Branch",
    role: "Agent",
    vouchers: 6,
    status: "Pending",
    dateCreated: "Apr 1, 2026",
    email: "ramon.garcia@standard.com",
    phone: "09171234573",
  },
  {
    id: 8,
    name: "Luz Fernandez",
    company: "Standard Insurance Co.",
    branch: "QC Branch",
    role: "Sub Agent",
    vouchers: 2,
    status: "Active",
    dateCreated: "Mar 15, 2026",
    email: "luz.fernandez@standard.com",
    phone: "09171234574",
  },
  {
    id: 9,
    name: "Ricardo Gomez",
    company: "Premier Insurance Corp",
    branch: "Main Branch",
    role: "Sub Agent",
    vouchers: 5,
    status: "Active",
    dateCreated: "Apr 10, 2026",
    email: "ricardo.gomez@premier.com",
    phone: "09171234575",
  },
  {
    id: 10,
    name: "Isabella Cruz",
    company: "Malayan Insurance Co.",
    branch: "Davao Branch",
    role: "Sub Agent",
    vouchers: 4,
    status: "Inactive",
    dateCreated: "Nov 20, 2025",
    email: "isabella.cruz@malayan.com",
    phone: "09171234576",
  },
];
