// mockLedger.js - Updated with more varied data
export const MOCK_TRANSACTIONS = [
  {
    action: "view",
    referenceNumber: "LA260528GGADQ0IZZBKO",
    account: {
      name: "Juan Dela Cruz",
      role: "Agent",
      companyBranch: "Sterling Insurance Company Inc - Manila",
    },
    voucher: "+10",
    oldTotalVouchers: 0,
    newTotalVouchers: 10,
    result: "Approved",
    dateCreated: "MAY 28, 2026 04:11 PM",
    type: "request",
    modalType: "cashin",
    transactionType: "CASHIN",
    status: "APPROVED",
  },
  {
    action: "view",
    referenceNumber: "LA260528GGADQ0IZZBKP",
    account: {
      name: "Maria Santos",
      role: "Senior Agent",
      companyBranch: "Sterling Insurance Company Inc - Cebu",
    },
    voucher: "+25",
    oldTotalVouchers: 15,
    newTotalVouchers: 40,
    result: "Approved",
    dateCreated: "MAY 28, 2026 02:30 PM",
    type: "request",
    modalType: "cashin",
    transactionType: "CASHIN",
    status: "APPROVED",
  },
  {
    action: "view",
    referenceNumber: "LA260528GGADQ0IZZBKQ",
    account: {
      name: "Roberto Reyes",
      role: "Manager",
      companyBranch: "Sterling Insurance Company Inc - Davao",
    },
    voucher: "-5",
    oldTotalVouchers: 50,
    newTotalVouchers: 45,
    result: "Approved",
    dateCreated: "MAY 27, 2026 11:15 AM",
    type: "adjustment",
    modalType: "addload",
    transactionType: "ADD_LOAD",
    status: "APPROVED",
    transfer: {
      company: "PACIFIC UNION INSURANCE COMPANY",
      referenceNumber: "LA260528QYA8557IFKBN",
      receiver: "RONALD DELA CRUZ",
      receiverRole: "Agent",
      from: "JUAN DELA CRUZ",
      fromRole: "Manager",
      processedBy: "JUAN DELA CRUZ",
      processedByRole: "Manager",
      balance: "+50",
    },
  },
  {
    action: "view",
    referenceNumber: "LA260527GGADQ0IZZBKR",
    account: {
      name: "Anna Fernandez",
      role: "Agent",
      companyBranch: "Sterling Insurance Company Inc - Manila",
    },
    voucher: "+15",
    oldTotalVouchers: 20,
    newTotalVouchers: 35,
    result: "Approved",
    dateCreated: "MAY 27, 2026 09:45 AM",
    type: "request",
    modalType: "cashin",
    transactionType: "CASHIN",
    status: "APPROVED",
  },
  {
    action: "view",
    referenceNumber: "TX260527GGADQ0IZZBKS",
    account: {
      name: "Ronald Dela Cruz",
      role: "Agent",
      companyBranch: "Sterling Insurance Company Inc - Makati",
    },
    voucher: "-1",
    oldTotalVouchers: 34,
    newTotalVouchers: 33,
    result: "Approved",
    dateCreated: "MAY 28, 2026 04:44 PM",
    type: "transaction",
    modalType: "transaction",
    transactionType: "TRANSACTION",
    status: "APPROVED",
    details: {
      status: "VERIFIED",
      company: "ALPHA INSURANCE AND SURETY COMPANY INC.",
      account: "RONALD DELA CRUZ",
      accountRole: "Agent",
      authenticationCode: "R123-456B-HWKM-Y7Z8",
    },
  },
];
