// constants/navigation.js
import {
  LayoutDashboard,
  Users,
  Building2,
  MapPin,
  Car,
  FileText,
  Activity,
  Shield,
  CreditCard,
  Ticket,
  ArrowLeftRight,
  BookOpen,
  HelpCircle, // Add for tickets icon
} from "lucide-react";

export const navConfig = {
  admin: [
    {
      id: "dashboard",
      label: "Dashboard",
      icon: LayoutDashboard,
      section: "MAIN",
      disabled: false,
    },
    {
      id: "tickets",
      label: "Tickets",
      icon: HelpCircle,
      section: "MAIN",
      disabled: false,
    },
    {
      id: "accounts",
      label: "Accounts",
      icon: Users,
      section: "ADMINISTRATION",
      disabled: false,
    },
    {
      id: "company",
      label: "Company",
      icon: Building2,
      section: "ADMINISTRATION",
      disabled: false,
    },
    {
      id: "branches",
      label: "Branches",
      icon: MapPin,
      section: "ADMINISTRATION",
      disabled: false,
    },
    {
      id: "vehicles",
      label: "Vehicle Database",
      icon: Car,
      section: "MANAGE",
      disabled: true,
    },
    {
      id: "mvtype",
      label: "MV Type",
      icon: FileText,
      section: "MANAGE",
      disabled: true,
    },
    {
      id: "activitylogs",
      label: "Activity Logs",
      icon: Activity,
      section: "MANAGE",
      disabled: false,
    },
    {
      id: "verification",
      label: "Verification",
      icon: Shield,
      section: "INSURANCE",
      disabled: false,
    },
    {
      id: "transactions",
      label: "Transactions",
      icon: CreditCard,
      section: "INSURANCE",
      disabled: false,
    },
    {
      id: "vouchers",
      label: "Vouchers",
      icon: Ticket,
      section: "INSURANCE",
      disabled: false,
    },
  ],
  viewer: [
    {
      id: "dashboard",
      label: "Dashboard",
      icon: LayoutDashboard,
      section: "MAIN",
      disabled: false,
    },
    {
      id: "tickets",
      label: "Support Tickets",
      icon: HelpCircle,
      section: "MAIN",
      disabled: false,
    },
    {
      id: "accounts",
      label: "Accounts",
      icon: Users,
      section: "ADMINISTRATION",
      disabled: false,
    },
    {
      id: "company",
      label: "Company",
      icon: Building2,
      section: "ADMINISTRATION",
      disabled: false,
    },
    {
      id: "branches",
      label: "Branches",
      icon: MapPin,
      section: "ADMINISTRATION",
      disabled: false,
    },
    {
      id: "vehicles",
      label: "Vehicle Database",
      icon: Car,
      section: "MANAGE",
      disabled: true,
    },
    {
      id: "mvtype",
      label: "MV Type",
      icon: FileText,
      section: "MANAGE",
      disabled: true,
    },
    {
      id: "activitylogs",
      label: "Activity Logs",
      icon: Activity,
      section: "MANAGE",
      disabled: false,
    },
    {
      id: "verification",
      label: "Verification",
      icon: Shield,
      section: "INSURANCE",
      disabled: false,
    },
    {
      id: "transactions",
      label: "Transactions",
      icon: CreditCard,
      section: "INSURANCE",
      disabled: false,
    },
    {
      id: "vouchers",
      label: "Vouchers",
      icon: Ticket,
      section: "INSURANCE",
      disabled: false,
    },
  ],
  manager: [
    {
      id: "dashboard",
      label: "Dashboard",
      icon: LayoutDashboard,
      section: "MAIN",
      disabled: false,
    },
    {
      id: "tickets",
      label: "Support Tickets",
      icon: HelpCircle,
      section: "MAIN",
      disabled: false,
    },
    {
      id: "accounts",
      label: "Accounts",
      icon: Users,
      section: "ADMINISTRATION",
      disabled: false,
    },
    {
      id: "company",
      label: "Company",
      icon: Building2,
      section: "ADMINISTRATION",
      disabled: false,
    },
    {
      id: "branches",
      label: "Branches",
      icon: MapPin,
      section: "ADMINISTRATION",
      disabled: false,
    },
    {
      id: "vouchers",
      label: "Vouchers",
      icon: Ticket,
      section: "VOUCHERS",
      disabled: false,
    },
    {
      id: "transfer-vouchers",
      label: "Transfer",
      icon: ArrowLeftRight,
      section: "VOUCHERS",
      disabled: false,
    },
    {
      id: "verification",
      label: "Verification",
      icon: Shield,
      section: "INSURANCE",
      disabled: false,
    },
    {
      id: "transactions",
      label: "Transactions",
      icon: CreditCard,
      section: "INSURANCE",
      disabled: false,
    },
    {
      id: "ledger",
      label: "Ledger",
      icon: BookOpen,
      section: "REPORTS",
      disabled: false,
    },
  ],
  agent: [
    {
      id: "dashboard",
      label: "Dashboard",
      icon: LayoutDashboard,
      section: "MAIN",
      disabled: false,
    },
    {
      id: "verification",
      label: "Verification",
      icon: Shield,
      section: "INSURANCE",
      disabled: false,
    },
    {
      id: "vouchers",
      label: "My Vouchers",
      icon: Ticket,
      section: "VOUCHERS",
      disabled: false,
    },
  ],
};
