export const VOUCHER_INVENTORY_STATUS = {
  AVAILABLE: "AVAILABLE",
  ASSIGNED: "ASSIGNED",
  USED: "USED",
  EXPIRED: "EXPIRED",
};

export const VOUCHER_INVENTORY_STATUS_LABELS = {
  [VOUCHER_INVENTORY_STATUS.AVAILABLE]: "Available",
  [VOUCHER_INVENTORY_STATUS.ASSIGNED]: "Assigned",
  [VOUCHER_INVENTORY_STATUS.USED]: "Used",
  [VOUCHER_INVENTORY_STATUS.EXPIRED]: "Expired",
};

export const VOUCHER_INVENTORY_FILTERS = [
  { id: "ALL", label: "All" },
  { id: VOUCHER_INVENTORY_STATUS.AVAILABLE, label: "Available" },
  { id: VOUCHER_INVENTORY_STATUS.ASSIGNED, label: "Assigned" },
  { id: VOUCHER_INVENTORY_STATUS.USED, label: "Used" },
  { id: VOUCHER_INVENTORY_STATUS.EXPIRED, label: "Expired" },
];
